[build]
  publish = "frontend"
  functions = "netlify/functions"
  command = "node netlify-deploy.js"
  
[build.environment]
  # MongoDB Configuration
  MONGODB_URI = "mongodb+srv://username:password@cluster.mongodb.net/rydo_db?retryWrites=true&w=majority"
  SESSION_SECRET = "rydo_secure_session_key_for_production_2025"
  GOOGLE_MAPS_API_KEY = "your_google_maps_api_key_here"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/verification/*"
  to = "/.netlify/functions/verification/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
