services:
  # Web service for the RYDO Web App
  - type: web
    name: rydo-web-app
    env: node
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
      - key: MONGODB_URI
        value: mongodb+srv://rydoapp:RydoApp2025!@rydo-cluster.mongodb.net/rydo_db?retryWrites=true&w=majority
      - key: SESSION_SECRET
        generateValue: true
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: EMAIL_SERVICE
        value: gmail
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RAZORPAY_COMMISSION_PERCENTAGE
        value: 7.5
